name: Тестирование Java-проекта с Maven и JDK 20

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run tests using Maven
        run: mvn -f untitled/pom.xml verify  # Сборка проекта и запуск тестов с помощью Maven

      - name: Generate test summary
        uses: djrbliss/gha-junit-test-summary@v1
        with:
          junit_xml_files: untitled/target/surefire-reports/*.xml  # Путь к результатам тестов
          markdown_report_file: 'report.md'  # Генерируемый отчет в Markdown

      - name: Create output
        id: create-output
        run: echo "::set-output name=report::$(cat report.md)"

      - name: Comment the pull request
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            #### 🚀 Тесты завершены!
            
            ${{ steps.create-output.outputs.report }}