name: Тестирование Java-проекта с Maven и JDK 20

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run tests using Maven
        run: mvn verify  # Сборка проекта и запуск тестов с помощью Maven

      - name: Show test results
        if: failure()  # Если тесты провалены
        run: |
          cd target/surefire-reports/
          ls -l
          cat TEST-*.xml  # Просмотр результатов тестирования