name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install -B --file pom.xml

      - name: Install 🔧
        run: npm install

      - name: Run Test 🔨
        run: npm run test

      - name: Generate test report
        run: mvn surefire-report:report-only

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/site/surefire-reports

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const report = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'target/site/surefire-reports/index.html',
              ref: context.sha
            });
            const reportContent = Buffer.from(report.data.content, 'base64').toString();
            const comment = `### Test Report\n\`\`\`html\n${reportContent}\n\`\`\``;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            });