name: Тестирование Java-проекта с Maven и JDK 20

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Checkstyle check
        run: |
          mvn checkstyle:check --no-transfer-progress

      - name: Run tests
        run: |
          mvn -f untitled/pom.xml

        env:
          CI: true

      - name: Build application
        run: |
          mvn verify --no-transfer-progress